# Generated by Django 4.1.3 on 2022-12-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_stamp", models.DateTimeField(auto_created=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
            ],
        ),
    ]
